
theme: jekyll-theme-minimal


nav:
  - title: "About"
    url: /#about
  - title: "Research"
    url: /#research
  - title: "Teaching"
    url: /#teaching
  - title: "Contact"
    url: /#contact


include: ["assets/css"]
