title: Mostafa El Sharkawy
description: PhD Candidate at the University of Michigan
theme: jekyll-theme-minimal

logo: assets/headshot.png

nav:
  - title: "About"
    url: /#about
  - title: "Research"
    url: /#research
  - title: "Teaching"
    url: /#teaching
  - title: "Contact"
    url: /#contact


include: ["assets/css"]
