title: Mostafa El Sharkawy

# Short, plain text: used by search engines & <meta name="description">
description: "Mostafa El Sharkawy"

# Custom variable: long HTML you want under your headshot
profile_description: |
  <strong>Ph.D. Candidate</strong><br>
  Department of Political Science<br>
  University of Michigan<br>
  📧 <a href="mailto:melshar@umich.edu">melshar@umich.edu</a><br>
  <a href="assets/CV.pdf">📄 CV</a> | 
  <a href="https://github.com/elsharkawy-mostafa">GitHub</a> | 
  <a href="https://x.com/SharkawiMostafa">X</a>

theme: jekyll-theme-minimal
logo: assets/headshot.png

nav:
  - title: "About"
    url: /
  - title: "Research"
    url: /research
  - title: "Teaching"
    url: /teaching
  - title: "Contact"
    url: /contact
