title: Mostafa El Sharkawy
description: Mostafa El Sharkawy

theme: jekyll-theme-minimal
logo: assets/headshot.png

nav:
  - title: "About"
    url: /
  - title: "Research"
    url: /research
  - title: "Teaching"
    url: /teaching
  - title: "Contact"
    url: /contact
